'use client';

import { useEffect, useState } from 'react';
import { useRouter, useParams } from 'next/navigation';

export default function InstructorCoursePage() {
  const router = useRouter();
  const { id: courseId } = useParams(); // Course ID from URL
  
  // Auth & role management
  const [roleChecked, setRoleChecked] = useState(false);
  const [userId, setUserId] = useState(null);

  // Week selection (1 to 10)
  const [selectedWeek, setSelectedWeek] = useState(1);

  // Uploaded segments for selected week
  const [segments, setSegments] = useState([]);

  // Selected segment index
  const [selectedSegmentIndex, setSelectedSegmentIndex] = useState(null);

  // Content of selected segment
  const [segmentContent, setSegmentContent] = useState(null);

  // MCQs generated by Teaching Assistant
  const [mcqs, setMcqs] = useState([]);
  const [loadingMCQs, setLoadingMCQs] = useState(false);

  // Loading states for segments and upload
  const [loadingSegments, setLoadingSegments] = useState(false);
  const [uploading, setUploading] = useState(false);
  
  // File upload state
  const [uploadFile, setUploadFile] = useState(null);

  // -----------------------------------------
  // Auth Check: Load user from localStorage, redirect if unauthorized
  useEffect(() => {
    const stored = typeof window !== 'undefined' ? localStorage.getItem('user') : null;
    if (!stored) {
      router.replace('/login');
      return;
    }
    try {
      const user = JSON.parse(stored);
      setUserId(user.id);
      if (user.role !== 'instructor') {
        router.replace('/student');
        return;
      }
      setRoleChecked(true);
    } catch {
      router.replace('/login');
    }
  }, [router]);

  // -----------------------------------------
  // Fetch segments for the selected week whenever courseId or selectedWeek changes
  useEffect(() => {
    if (!roleChecked || !userId) return;
    fetchSegments();
  }, [roleChecked, userId, courseId, selectedWeek]);

  // -----------------------------------------
  // Fetch segments from backend for this course and week
  async function fetchSegments() {
    setLoadingSegments(true);
    try {
      const res = await fetch(
        `http://localhost:8000/api/segments?course_id=${courseId}&week=${selectedWeek}`
      );
      if (!res.ok) throw new Error('Failed to fetch segments.');
      const data = await res.json();
      setSegments(data || []);
      if (data && data.length > 0) {
        setSelectedSegmentIndex(0);
        setSegmentContent(data[0].content);
        setMcqs([]); // Clear old MCQs when segments update
      } else {
        setSelectedSegmentIndex(null);
        setSegmentContent(null);
        setMcqs([]);
      }
    } catch (err) {
      alert(err.message || 'Error fetching segments.');
    }
    setLoadingSegments(false);
  }
  
  // -----------------------------------------
  // Handle file input change
  function onFileChange(e) {
    setUploadFile(e.target.files?.[0] || null);
  }

  // -----------------------------------------
  // Upload the lecture file for selected week
  async function handleUpload(e) {
    e.preventDefault();
    if (!uploadFile) {
      alert('Please select a file to upload.');
      return;
    }
    setUploading(true);

    try {
      // Assuming backend expects multipart/form-data for upload
      const formData = new FormData();
      formData.append('file', uploadFile);
      formData.append('course_id', courseId);
      formData.append('week', selectedWeek);

      const res = await fetch('http://localhost:8000/api/upload-lecture/', {
        method: 'POST',
        body: formData,
      });

      if (!res.ok) throw new Error('Upload failed.');

      alert('Upload successful! Parsing file...');

      // Refresh segments after upload completes and is parsed
      fetchSegments();
      setUploadFile(null);
      e.target.reset(); // reset file input UI

    } catch (err) {
      alert(err.message || 'Failed to upload file.');
    }
    setUploading(false);
  }

  // -----------------------------------------
  // Handle user clicking on a segment title
  function handleSegmentClick(index) {
    if (index === selectedSegmentIndex) return;
    setSelectedSegmentIndex(index);
    setSegmentContent(segments[index].content);
    setMcqs([]);
  }

  // -----------------------------------------
  // Generate MCQs for selected segment
  async function generateMCQs() {
    if (selectedSegmentIndex === null || !segments[selectedSegmentIndex]) return;
    setLoadingMCQs(true);
    setMcqs([]);

    try {
      const segment = segments[selectedSegmentIndex];
      // Call the backend RAG endpoint
      const res = await fetch('http://localhost:8000/api/generate-mcqs/', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          course_id: courseId,
          week: selectedWeek,
          segment_index: segment.segment_index,
          content: segment.content,
        }),
      });
      if (!res.ok) throw new Error('Failed to generate MCQs.');
      const data = await res.json();
      setMcqs(data.mcqs || []);
    } catch (err) {
      alert(err.message || 'Error generating MCQs.');
    }
    setLoadingMCQs(false);
  }

  // -----------------------------------------
  // UI Components rendering

  // Sidebar: weeks 1 to 10
  const WeekSelector = () => (
    <div className="w-40 border-r border-gray-300 p-4">
      <h3 className="font-semibold mb-2">Select Week</h3>
      <ul>
        {[...Array(10).keys()].map((w) => {
          const weekNumber = w + 1;
          return (
            <li key={weekNumber}>
              <button
                className={`block w-full text-left px-2 py-1 rounded hover:bg-gray-200 ${
                  selectedWeek === weekNumber ? 'bg-gray-300 font-semibold' : ''
                }`}
                onClick={() => setSelectedWeek(weekNumber)}
              >
                Week {weekNumber}
              </button>
            </li>
          );
        })}
      </ul>
    </div>
  );

  // Segment list with clickable titles
  const SegmentList = () => (
    <div className="border-b border-gray-300 py-2 overflow-auto max-h-[200px]">
      <ul>
        {segments.map((segment, idx) => (
          <li key={segment.id}>
            <button
              className={`block w-full text-left px-2 py-1 rounded hover:bg-gray-200 ${
                selectedSegmentIndex === idx ? 'bg-gray-300 font-semibold' : ''
              }`}
              onClick={() => handleSegmentClick(idx)}
            >
              {segment.title || `Slide ${segment.segment_index + 1}`}
            </button>
          </li>
        ))}
      </ul>
    </div>
  );

  // Slide content viewer
  const SlideViewer = () => (
    <div className="p-4 border border-gray-300 rounded shadow-sm overflow-auto h-64 whitespace-pre-wrap bg-white">
      {segmentContent || <p>No content available.</p>}
    </div>
  );

  // Teaching assistant MCQ display component
  const TeachingAssistant = () => (
    <div className="mt-4">
      <button
        className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition"
        onClick={generateMCQs}
        disabled={loadingMCQs || selectedSegmentIndex === null}
      >
        {loadingMCQs ? 'Generating MCQs...' : 'Teaching Assistant: Generate MCQs'}
      </button>

      {mcqs.length > 0 && (
        <div className="mt-4 bg-gray-100 p-4 rounded shadow">
          <h4 className="font-semibold mb-2">Generated MCQs</h4>
          <ul className="list-decimal list-inside space-y-2">
            {mcqs.map((mcq, i) => (
              <li key={i}>
                <p className="font-medium">{mcq.question}</p>
                <ul className="list-disc list-inside ml-4">
                  {mcq.options.map((opt, idx) => (
                    <li key={idx} className={opt === mcq.answer ? 'font-bold text-green-600' : ''}>
                      {opt}
                    </li>
                  ))}
                </ul>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );

  // --------------------------------------------------
  if (!roleChecked) {
    return <div className="p-8">Checking authorization...</div>;
  }

  if (loadingSegments) {
    return <div className="p-8">Loading segments...</div>;
  }

  return (
    <div className="flex max-w-6xl mx-auto h-[80vh] border rounded shadow">
      {/* Sidebar week selector */}
      <WeekSelector />

      {/* Main Content */}
      <div className="flex-1 flex flex-col p-6 bg-gray-50 space-y-4">
        {/* Upload Form */}
        <form className="flex items-center gap-4" onSubmit={handleUpload}>
          <input
            type="file"
            accept=".pdf, .pptx"
            onChange={onFileChange}
            className="border rounded px-2 py-1"
            required
            name="lectureFile"
            id="lectureFile"
          />
          <button
            type="submit"
            disabled={uploading}
            className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700 transition"
          >
            {uploading ? 'Uploading...' : 'Upload Lecture Material'}
          </button>
        </form>

        {/* Segment List and Viewer */}
        <div className="flex-1 flex space-x-4 overflow-hidden">
          <div className="w-1/3 overflow-auto border rounded bg-white shadow-sm">
            <SegmentList />
          </div>
          <div className="flex-1 flex flex-col">
            <SlideViewer />
            <TeachingAssistant />
          </div>
        </div>
      </div>
    </div>
  );
}
